collections:
  authors:
    output: true
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
sass:
  sass_dir: _sass
  style: compressed
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag